apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "another-set-on-diff-master"
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: git@github.com:tarteo/test-set.git
      revision: set-1
      files:
      - path: instances2/**/config.yaml
  template:
    metadata:
      name: "{{ .path.basename }}"
      labels:
        applicationSet: "another-set-on-diff-master"
    spec:
      project: "default"
      source:
        repoURL: git@github.com:tarteo/test-set.git
        targetRevision: set-1
        path: app
        helm:
          values: |
            {{ .helm }}
      destination:
        name: in-cluster
        namespace: "{{ .path.basename }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: false
          selfHeal: false
        